api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path("", views.index, name="index"),
    # path("login", views.login_view, name="login"),
    # path("logout", views.logout_view, name="logout"),
    # path("register", views.register, name="register")
]

network/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("", views.index, name="index"),
    path("user/<str:user_id>", views.user_page, name="user"),
    path("user/<str:user_id>/following", views.following_page, name="following"),
    path("user/<str:user_id>/follow", views.follow_or_unfollow, name="follow_or_unfollow"),
    path("tweet/<str:tweet_id>/like", views.like_or_dislike, name="like_or_dislike"),
    path("tweet/<str:tweet_id>/edit", views.edit, name="tweet_edit"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

api/models.py
from django.db import models

# Create your models here.

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    folowing = models.ManyToManyField('User', blank=True, related_name='folowers')
    pass


class Tweet(models.Model):
    # title = models.CharField(max_length=32)
    body = models.CharField(max_length=256)
    created_on = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tweets')
    likes = models.ManyToManyField(User, blank=True, related_name='favs')

    def __str__(self):
        return f'{self.owner}: {self.body[:50]}'

    class Meta:
        ordering = ['-created_on']

api/views.py
from django.shortcuts import render
from rest_framework import viewsets

from network.models import User, Tweet
from .serializers import CatSerializer
# Create your views here.

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django import forms
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .models import User, Tweet


class NewTweet(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class': "form-control", 'placeholder': "What you want say to the word?"}),
        }


def index(request):
    if request.method == "POST":
        form = NewTweet(request.POST)
        # if new form for tweet fill corectly -> save to db
        if form.is_valid():
            Tweet.objects.create(owner=request.user, body=form.cleaned_data['body'])
            # load page with new tweet
            return HttpResponseRedirect(reverse("tweets:index"))
    else:
        form = NewTweet()

    tweets = Tweet.objects.all()
    paginator = Paginator(tweets, 10)
    page_number = request.GET.get('page')
    tweets_on_page = paginator.get_page(page_number)

    return render(request, "network/index.html", {
            "form": form,
            "title": "All tweets:",
            "userpage": None,
            "tweets_page": tweets_on_page
        })


def user_page(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    # Disable form if it's page other user
    if user != request.user:
        form = None

    # Enable form and POST query if it's yourself page
    elif request.method == "POST":
        form = NewTweet(request.POST)
        # if new form for lot fill corectly -> save to db
        if form.is_valid():
            Tweet.objects.create(owner=request.user, body=form.cleaned_data['body'])
            # load page with new tweet
            return HttpResponseRedirect(reverse("tweets:index", args=(user_id)))
    else:
        form = NewTweet()

    tweets = Tweet.objects.filter(owner=user_id)
    paginator = Paginator(tweets, 10)
    page_number = request.GET.get('page')
    tweets_on_page = paginator.get_page(page_number)

    return render(request, "network/index.html", {
            "form": form,
            "title": f"{user} tweets:",
            "userpage": user,
            "tweets_page": tweets_on_page
        })


def following_page(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    # Disable newtweet form
    form = None

    tweets = Tweet.objects.filter(owner__in=user.folowing.all())
    paginator = Paginator(tweets, 10)
    page_number = request.GET.get('page')
    tweets_on_page = paginator.get_page(page_number)

    return render(request, "network/index.html", {
            "form": form,
            "title": f"{user} following tweets:",
            "userpage": user,
            "tweets_page": tweets_on_page
        })


@login_required
def follow_or_unfollow(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    if user != request.user:

        # Unfollow user_id from current loggin user
        if user in request.user.folowing.all():
            request.user.folowing.remove(user)
        # Follow
        else:
            request.user.folowing.add(user)

    return HttpResponseRedirect(reverse("tweets:user", args=(user_id)))


@login_required
def like_or_dislike(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)

    # dislike
    if request.user in tweet.likes.all():
        tweet.likes.remove(request.user)
    # like
    else:
        tweet.likes.add(request.user)

    return HttpResponse(status=204)


@login_required
def edit(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)

    # User try edit not your tweet
    if request.user != tweet.owner:
        return HttpResponse(status=406)

    if request.method == "PUT":
        data = json.loads(request.body)
        print(f"\ndata: {data}")
        if data.get("text") is not None:
            tweet.body = data["text"]
        else:
            JsonResponse({"new_text": tweet.body}, status=201)

        try:
            tweet.save()
        except:
            return JsonResponse({'error': 'incorrect data in text field'}, status=422)

    print(f"\nNew tweet text {tweet.body}")
    return JsonResponse({"new_text": tweet.body}, status=201)



def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("tweets:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("tweets:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("tweets:index"))
    else:
        return render(request, "network/register.html")

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
  <div class="row justify-content-center p-2">
    <div class="col-12 col-sm-10 col-md-6 col-lg-4">

    <!--Если это страница пользователя, отображаем имя, кол-во и ссылку на ленту фолловеров и кнопку подписаться -->
    {% if userpage is not None %}
      <div class="p-3 border-bottom" id="follows_block">
        <span class='h4'>@{{ userpage }}</span>
        &nbsp&nbsp
        <a href="{% url 'tweets:following' userpage.id %}" class="black_text">{{ userpage.folowing.all | length }}<span class='follow_text'> Following</span></a>
        &nbsp&nbsp
        <a href="#" class="black_text">{{ userpage.folowers.all | length }} <span class='follow_text'> Followers</span></a>

        <!--add follow/unfollow button for authorisated users -->
        {% if user.is_authenticated and userpage.id != user.id %}
          {% if userpage in user.folowing.all %}
              <a href="{% url 'tweets:follow_or_unfollow' userpage.id %}" class="btn btn-sm btn-success m-2">Unfollow</a>
          {% else %}
              <a href="{% url 'tweets:follow_or_unfollow' userpage.id %}" class="btn btn-sm btn-success m-2">Follow</a>
          {% endif %}
        {% endif %}
      </div>
    {% endif %}

    <!--Если пользоваль залогинен и находится на своей или общей ленте - то отображаем форму для нового твита-->
    {% if user.is_authenticated and form is not None%}
      <row id='form_tweet'>
        <div class="border border-info">
          <form class="form-group p-2 mb-0" action="{% url 'tweets:index' %}"  method="post">
            <h6>New post</h6>
            {% csrf_token %}
            {{ form.body.errors }}
            {{ form.body }}
            <button class="btn btn-sm btn-primary mt-1" type="submit">Post</button>
          </form>
        </div>
      </row>
    {% endif %}

    <div class="pt-4 pb-2">
        <h5 id="title_block">{{ title }}</h5>
    </div>

    <!--Tweets block-->
    {% for tweet in tweets_page %}
      <div class="row-justify pb-4">
        <div class="card">
          <div class="card-header">
            @<a href="{% url 'tweets:user' tweet.owner.id %}" class="hrefuser">{{ tweet.owner }}</a>
          </div>

          <div id="body_{{ tweet.id }}" class="card-body">
            <div id="text_{{ tweet.id }}" data-body="{{ tweet.body }}" class="card-text">
                <span>{{ tweet.body }}</span>
              {% if user.is_authenticated and user == tweet.owner %}
                <button type="button" class="btn btn-sm btn-link float-right edit" data-id="{{ tweet.id }}">edit</button>
              {% endif %}
            </div>
            <form class="tweet_form" id="form_{{ tweet.id }}" data-id="{{ tweet.id }}" style="display: none;">
              {% csrf_token %}
              <textarea class="form-control p-1" name="text" id="textarea_{{ tweet.id }}" rows="3">{{ tweet.body }}</textarea>
              <button type="submit" class="btn btn-outline-info btn-sm float-right mt-1">Save</button>
            </form>
          </div>

          <div class="card-footer">
            {% if user in tweet.likes.all %}
                <button class="btn btn-default fa fa-heart likes" data-id="{{ tweet.id }}" style="color:red;">
            {% else %}
                <button class="btn btn-default fa fa-heart-o likes" data-id="{{ tweet.id }}" style="color:red;">
            {% endif %}

              <span id="likes_for_{{ tweet.id }}" style="color:gray;">{{ tweet.likes.all | length }}</span>
            </button>
            <span class="text-muted float-right" style="font-size: 80%;">{{ tweet.created_on }}</span>
          </div>
        </div>
      </div>

    {% endfor %}

    <!--Pagindation-->
    <!--<div class="pagination">-->
    <!--  <span class="step-links">-->
    <!--    {% if tweets_page.has_previous %}-->
    <!--      <a href="?page=1">&laquo; first</a>-->
    <!--      <a href="?page={{ tweets_page.previous_page_number }}">previous</a>-->
    <!--    {% endif %}-->

    <!--    <span class="current">-->
    <!--      Page {{ tweets_page.number }} of {{ tweets_page.paginator.num_pages }}.-->
    <!--    </span>-->

    <!--    {% if tweets_page.has_next %}-->
    <!--      <a href="?page={{ tweets_page.next_page_number }}">next</a>-->
    <!--      <a href="?page={{ tweets_page.paginator.num_pages }}">last &raquo;</a>-->
    <!--    {% endif %}-->
    <!--  </span>-->
    <!--</div>-->


    <nav aria-label="navigation">
      <ul class="pagination justify-content-center">

        {% if tweets_page.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1}">First</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ tweets_page.previous_page_number }}">{{ tweets_page.previous_page_number }}</a>
          </li>

        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">First</a>
          </li>
        {% endif %}

         <!--Active page-->
        <li class="page-item active">
            <a class="page-link" href="#">{{ tweets_page.number }}</a>
        </li>

        {% if tweets_page.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ tweets_page.next_page_number }}">{{ tweets_page.next_page_number }}</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ tweets_page.paginator.num_pages }}">Last</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="?page={{ tweets_page.paginator.num_pages }}">Last</a>
          </li>
        {% endif %}

      </ul>
    </nav>

    </div>
  </div>

{% endblock %}

{% block script %}
    <script src="{% static 'network/index.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        {% block script %}
        {% endblock %}

    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'tweets:index' %}">Network</a>

            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweets:user' user.id %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'tweets:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweets:following' user.id %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweets:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweets:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweets:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>

        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'tweets:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'tweets:register' %}">Register here.</a>

{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'tweets:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'tweets:login' %}">Log In here.</a>

{% endblock %}